[package]
name = "ciri"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clutils = "0.0.7"
frontend = { path = "../frontend"}
