[workspace]
members = [
    "api",       # Developer api
    "frontend",  # ir-compiler
    "middleend", # optimizer
    "backend",   # machine code compiler
    "test-lang", # language for testing
    "fungus",    # rust compiler
]
resolver = "2"