[workspace]
members = [
    "crates/api",       # Developer api
    "crates/frontend",  # ir-compiler
    "crates/middleend", # optimizer
    "crates/backend",   # machine code compiler
    "crates/test-lang", # language for testing
    "crates/fungus",    # rust compiler
    "crates/ciri",      # IR Interpreter
]
resolver = "2"
