[package]
name = "test-lang"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clutils = "0.0.9"
citadel-frontend = { path = "../frontend"}
citadel-backend = { path = "../backend" }