[package]
name = "citadel-api"
version = "0.0.12"
edition = "2021"
license = "MIT"
readme = "README.md"
description = "The api for the citadel compiler backend"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
citadel-frontend = { path = "../frontend", version = "0.0.12" }
citadel-middleend = { path = "../middleend", version = "0.0.11" }
citadel-backend = { path = "../backend", version = "0.0.11" }
